name: Build Gradle project
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build with Gradle
        run: cd backend && gradle build -x test -x checkstyleMain -x checkstyleTest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Test with Gradle
        run: cd backend && gradle jacocoTestCoverageVerification
